service: rank-app

provider:
  name: aws
  runtime: go1.x
  profile: uptactics
  memorySize: 128
  region: us-east-1 # US East 1 (N. Virginia)
  stage: ${opt:stage, 'staging'}
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    # Only allow to a specific dynamo db table
    - Effect: Allow
      Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.tableName}*'
      Action:
        - "dynamodb:*"
    # S3 iam roles
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket
        - s3:ListBucketVersions
      Resource:
        - 'arn:aws:s3:::${self:custom.bucketName}'
        - 'arn:aws:s3:::${self:custom.bucketName}/*'
    # Allow all SNS + Xray + ElasticSearch
    - Effect: "Allow"
      Resource: "*"
      Action:
        - sns:*
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
        - es:*

functions:
  # == HTTP ==
  SayHello:
    handler: bin/SayHello
    events:
      - http:
          path: /hello
          method: post

  DownloadLatestCSV:
    handler: bin/DownloadLatestCSV
    timeout: 30
    events:
      - http:
          path: /download-latest-csv
          method: get
    environment:
      S3_BUCKET_NAME: ${self:custom.env.S3_BUCKET_NAME}

  # == CRON ==
  RunCrawl:
    handler: bin/RunCrawl
    events:
      - schedule: cron(0 10 * * ? *)
    environment:
      SNS_PREFIX: ${self:custom.env.SNS_PREFIX}
      KEYWORDS: ${self:custom.env.KEYWORDS}

  UpdateLatestCSV:
    handler: bin/UpdateLatestCSV
    timeout: 120
    events:
      - schedule: cron(0 11 * * ? *)
    environment:
      S3_BUCKET_NAME: ${self:custom.env.S3_BUCKET_NAME}
      DB_TABLE_NAME: ${self:custom.env.DB_TABLE_NAME}

  # == SNS ==
  ProcessKeyword:
    handler: bin/ProcessKeyword
    events:
      - sns: ${self:service}-${self:provider.stage}-ProcessKeyword
    timeout: 60 # 1 Minute timeout to fetch data from Zenserp
    environment:
      ZENSERP_API_KEY: ${self:custom.env.ZENSERP_API_KEY}
      DB_TABLE_NAME: ${self:custom.env.DB_TABLE_NAME}
      SNS_PREFIX: ${self:custom.env.SNS_PREFIX}

  AddCrawlResultToLatest:
    handler: bin/AddCrawlResultToLatest
    events:
      - sns: ${self:service}-${self:provider.stage}-CrawlResultCreated
    environment:
      DB_TABLE_NAME: ${self:custom.env.DB_TABLE_NAME}

  # == ADHOC FUNCTONS ==
  UpdateResultItemIndexMapping:
    handler: bin/UpdateResultItemIndexMapping
    timeout: 60 # 1 Minute timeout
    environment:
      ELASTICSEARCH_URL: ${self:custom.env.ELASTICSEARCH_URL}

custom:
  tableName: ${self:service}-${self:provider.stage}
  bucketName: ${self:service}-${self:provider.stage}
  esName: ${self:service}-${self:provider.stage}

  env:
    SNS_PREFIX: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${self:service}-${self:provider.stage}'
    KEYWORDS: ${ssm:/${self:service}/${self:provider.stage}/KEYWORDS}
    ZENSERP_API_KEY: ${ssm:/${self:service}/${self:provider.stage}/ZENSERP_API_KEY~true}
    DB_TABLE_NAME: ${self:custom.tableName}
    S3_BUCKET_NAME: ${self:custom.bucketName}
    ELASTICSEARCH_URL:
      Fn::GetAtt: ["RankElasticsearch", "DomainEndpoint"]

  staging:
    elasticsearchResource:
      Type: "AWS::Elasticsearch::Domain"
      Properties:
        ElasticsearchVersion: "7.9"
        DomainName: ${self:custom.esName}
        ElasticsearchClusterConfig:
          DedicatedMasterEnabled: false
          InstanceCount: "1"
          ZoneAwarenessEnabled: false
          InstanceType: "t2.small.elasticsearch"
        EBSOptions:
          EBSEnabled: true
          Iops: 0
          VolumeSize: 10
          VolumeType: "gp2"
        AdvancedOptions:
          rest.action.multi.allow_explicit_index: "true"
        AccessPolicies:
          Version: "2012-10-17"
          Statement:
            Effect: "Allow"
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${self:service}-${self:provider.stage}-${self:provider.region}-lambdaRole'
            Action: "es:*"
            Resource: "*"

  production:
    elasticsearchResource:
      Type: "AWS::Elasticsearch::Domain"
      Properties:
        ElasticsearchVersion: "7.9"
        DomainName: ${self:custom.esName}
        ElasticsearchClusterConfig:
          DedicatedMasterEnabled: false
          InstanceCount: "2"
          ZoneAwarenessEnabled: false
          InstanceType: "t2.medium.elasticsearch"
        EBSOptions:
          EBSEnabled: true
          Iops: 0
          VolumeSize: 10
          VolumeType: "gp2"
        AdvancedOptions:
          rest.action.multi.allow_explicit_index: "true"
        AccessPolicies:
          Version: "2012-10-17"
          Statement:
            Effect: "Allow"
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${self:service}-${self:provider.stage}-${self:provider.region}-lambdaRole'
            Action: "es:*"
            Resource: "*"

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI-SK-PK # Inverted PK/SK
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
              - AttributeName: PK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        VersioningConfiguration:
          Status: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT]
              AllowedOrigins: ['*']
              Id: CORSRuleId1
              MaxAge: '3600'

    RankElasticsearch: ${self:custom.${self:provider.stage}.elasticsearchResource}
