service: rank-app

provider:
  name: aws
  runtime: go1.x
  profile: uptactics
  memorySize: 128
  region: ap-southeast-2
  stage: ${opt:stage, 'staging'}
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true

functions:
  SayHello:
    handler: bin/SayHello
    events:
      - http:
          path: /hello
          method: post
